alias b := build
alias c := clean


#  GIT SUBMODULE CMD MESSAGES (entered from repository root directory)
#  git submodule add -b "master" 'https://github.com/STMicroelectronics/stm32g4xx_hal_driver.git' 'software/opendulum_sw_proj/source/vendor/STM32G4xx_HAL_Driver'
#  git submodule add -b "master" 'https://github.com/STMicroelectronics/cmsis_device_g4.git' 'software/opendulum_sw_proj/source/vendor/cmsis_device_g4'


set shell := ["powershell.exe", "/c"]

build_folder_path := absolute_path('build')

clean_command_string := if path_exists(build_folder_path) == "true" {
    'Remove-Item -Path "./build" -Recurse -Force'
} else {
    'echo "nothing to clean"'
}

build:
    cmake -DCMAKE_TOOLCHAIN_FILE="cubeide-gcc.cmake" -S ./ -B build -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=build
    make -C build VERBOSE=1 -j

clean:
    {{clean_command_string}}

